-- Insert Teams data
INSERT INTO Teams (team_name, group_letter, matches_played, wins, draws, losses, goals_for, goals_against, goal_difference, points, group_rank)
VALUES 
('Netherlands', 'A', 3, 2, 1, 0, 5, 1, 4, 7, 1),
('Senegal', 'A', 3, 2, 0, 1, 5, 4, 1, 6, 2),
('Ecuador', 'A', 3, 1, 1, 1, 4, 3, 1, 4, 3),
('Qatar', 'A', 3, 0, 0, 3, 1, 7, -6, 0, 4),
('England', 'B', 3, 2, 1, 0, 9, 2, 7, 7, 1),
('USA', 'B', 3, 1, 2, 0, 2, 1, 1, 5, 2),
('Iran', 'B', 3, 1, 0, 2, 4, 7, -3, 3, 3),
('Wales', 'B', 3, 0, 1, 2, 1, 6, -5, 1, 4),
('Argentina', 'C', 3, 2, 0, 1, 5, 2, 3, 6, 1),
('Poland', 'C', 3, 1, 1, 1, 2, 2, 0, 4, 2),
('Mexico', 'C', 3, 1, 1, 1, 2, 3, -1, 4, 3),
('Saudi Arabia', 'C', 3, 1, 0, 2, 3, 5, -2, 3, 4),
('France', 'D', 3, 2, 0, 1, 6, 3, 3, 6, 1),
('Australia', 'D', 3, 2, 0, 1, 3, 4, -1, 6, 2),
('Tunisia', 'D', 3, 1, 1, 1, 1, 1, 0, 4, 3),
('Denmark', 'D', 3, 0, 1, 2, 1, 3, -2, 1, 4),
('Japan', 'E', 3, 2, 0, 1, 4, 3, 1, 6, 1),
('Spain', 'E', 3, 1, 1, 1, 9, 3, 6, 4, 2),
('Germany', 'E', 3, 1, 1, 1, 6, 5, 1, 4, 3),
('Costa Rica', 'E', 3, 1, 0, 2, 3, 11, -8, 3, 4),
('Morocco', 'F', 3, 2, 1, 0, 4, 1, 3, 7, 1),
('Croatia', 'F', 3, 1, 2, 0, 4, 1, 3, 5, 2),
('Belgium', 'F', 3, 1, 1, 1, 1, 2, -1, 4, 3),
('Canada', 'F', 3, 0, 0, 3, 2, 7, -5, 0, 4),
('Brazil', 'G', 3, 2, 0, 1, 3, 1, 2, 6, 1),
('Switzerland', 'G', 3, 2, 0, 1, 4, 3, 1, 6, 2),
('Cameroon', 'G', 3, 1, 1, 1, 4, 4, 0, 4, 3),
('Serbia', 'G', 3, 0, 1, 2, 5, 8, -3, 1, 4),
('Portugal', 'H', 3, 2, 0, 1, 6, 4, 2, 6, 1),
('South Korea', 'H', 3, 1, 1, 1, 4, 4, 0, 4, 2),
('Uruguay', 'H', 3, 1, 1, 1, 2, 2, 0, 4, 3),
('Ghana', 'H', 3, 1, 0, 2, 5, 7, -2, 3, 4);

-- Insert Stadiums data
INSERT INTO Stadiums (stadium_name, city, country, capacity)
VALUES 
('Lusail Iconic Stadium', 'Lusail', 'Qatar', 88966),
('Al Bayt Stadium', 'Al Khor', 'Qatar', 68895),
('Khalifa International Stadium', 'Al Rayyan', 'Qatar', 45857),
('Ahmad bin Ali Stadium', 'Al Rayyan', 'Qatar', 45032),
('Education City Stadium', 'Al Rayyan', 'Qatar', 44667),
('Al Thumama Stadium', 'Doha', 'Qatar', 44400),
('Stadium 974', 'Doha', 'Qatar', 44089),
('Al Janoub Stadium', 'Al Wakrah', 'Qatar', 44325);

-- Insert Referees data
INSERT INTO Referees (referee_name, country)
VALUES 
('Daniele Orsato', 'Italy'),
('Raphael Claus', 'Brazil'),
('Wilton Sampaio', 'Brazil'),
('Abdulrahman Al-Jassim', 'Qatar'),
('Slavko Vinčić', 'Slovenia'),
('César Ramos', 'Mexico'),
('Chris Beath', 'Australia'),
('Victor Gomes', 'South Africa'),
('Fernando Rapallini', 'Argentina'),
('Iván Barton', 'El Salvador'),
('Mohammed Abdulla Hassan', 'UAE'),
('Janny Sikazwe', 'Zambia'),
('Facundo Tello', 'Argentina'),
('Clément Turpin', 'France'),
('Ismail Elfath', 'USA'),
('Mario Escobar', 'Guatemala'),
('Antonio Mateu Lahoz', 'Spain'),
('Mustapha Ghorbal', 'Algeria'),
('Jesús Valenzuela', 'Venezuela'),
('Daniel Siebert', 'Germany'),
('Szymon Marciniak', 'Poland'),
('Michael Oliver', 'England'),
('Andrés Matonte', 'Uruguay'),
('Danny Makkelie', 'Netherlands'),
('Anthony Taylor', 'England'),
('Bakary Gassama', 'Gambia'),
('Matthew Conger', 'New Zealand'),
('Stéphanie Frappart', 'France');

-- Insert Players data
INSERT INTO Players (player_name, position, club, team_id, goals_scored)
VALUES 
('Kylian Mbappé', 'Forward', 'Paris Saint-Germain', (SELECT team_id FROM Teams WHERE team_name = 'France'), 8),
('Lionel Messi', 'Forward', 'Paris Saint-Germain', (SELECT team_id FROM Teams WHERE team_name = 'Argentina'), 7),
('Julián Álvarez', 'Forward', 'Manchester City', (SELECT team_id FROM Teams WHERE team_name = 'Argentina'), 4),
('Olivier Giroud', 'Forward', 'AC Milan', (SELECT team_id FROM Teams WHERE team_name = 'France'), 4),
('Richarlison', 'Forward', 'Tottenham Hotspur', (SELECT team_id FROM Teams WHERE team_name = 'Brazil'), 3),
('Enner Valencia', 'Forward', 'Fenerbahçe', (SELECT team_id FROM Teams WHERE team_name = 'Ecuador'), 3),
('Marcus Rashford', 'Forward', 'Manchester United', (SELECT team_id FROM Teams WHERE team_name = 'England'), 3),
('Bukayo Saka', 'Forward', 'Arsenal', (SELECT team_id FROM Teams WHERE team_name = 'England'), 3),
('Cody Gakpo', 'Forward', 'PSV Eindhoven', (SELECT team_id FROM Teams WHERE team_name = 'Netherlands'), 3),
('Gonçalo Ramos', 'Forward', 'Benfica', (SELECT team_id FROM Teams WHERE team_name = 'Portugal'), 3),
('Álvaro Morata', 'Forward', 'Atlético Madrid', (SELECT team_id FROM Teams WHERE team_name = 'Spain'), 3),
('Neymar', 'Forward', 'Paris Saint-Germain', (SELECT team_id FROM Teams WHERE team_name = 'Brazil'), 2),
('Vincent Aboubakar', 'Forward', 'Al Nassr', (SELECT team_id FROM Teams WHERE team_name = 'Cameroon'), 2),
('Andrej Kramarić', 'Forward', 'Hoffenheim', (SELECT team_id FROM Teams WHERE team_name = 'Croatia'), 2),
('Niclas Füllkrug', 'Forward', 'Werder Bremen', (SELECT team_id FROM Teams WHERE team_name = 'Germany'), 2),
('Kai Havertz', 'Midfielder', 'Chelsea', (SELECT team_id FROM Teams WHERE team_name = 'Germany'), 2),
('Mohammed Kudus', 'Midfielder', 'Ajax', (SELECT team_id FROM Teams WHERE team_name = 'Ghana'), 2),
('Mehdi Taremi', 'Forward', 'FC Porto', (SELECT team_id FROM Teams WHERE team_name = 'Iran'), 2),
('Ritsu Dōan', 'Midfielder', 'SC Freiburg', (SELECT team_id FROM Teams WHERE team_name = 'Japan'), 2),
('Youssef En-Nesyri', 'Forward', 'Sevilla', (SELECT team_id FROM Teams WHERE team_name = 'Morocco'), 2),
('Breel Embolo', 'Forward', 'AS Monaco', (SELECT team_id FROM Teams WHERE team_name = 'Switzerland'), 2),
('Robert Lewandowski', 'Forward', 'FC Barcelona', (SELECT team_id FROM Teams WHERE team_name = 'Poland'), 2),
('Bruno Fernandes', 'Midfielder', 'Manchester United', (SELECT team_id FROM Teams WHERE team_name = 'Portugal'), 2),
('Rafael Leão', 'Forward', 'AC Milan', (SELECT team_id FROM Teams WHERE team_name = 'Portugal'), 2),
('Salem Al-Dawsari', 'Midfielder', 'Al-Hilal', (SELECT team_id FROM Teams WHERE team_name = 'Saudi Arabia'), 2),
('Aleksandar Mitrović', 'Forward', 'Fulham', (SELECT team_id FROM Teams WHERE team_name = 'Serbia'), 2),
('Ferran Torres', 'Forward', 'FC Barcelona', (SELECT team_id FROM Teams WHERE team_name = 'Spain'), 2),
('Cho Gue-sung', 'Forward', 'Jeonbuk Hyundai Motors', (SELECT team_id FROM Teams WHERE team_name = 'South Korea'), 2);

-- Insert Matches data
INSERT INTO Matches (match_date, stage, team1_id, team2_id, team1_score, team2_score, stadium_id, attendance, referee_id)
VALUES 
('2022-11-20', 'Group A', 
 (SELECT team_id FROM Teams WHERE team_name = 'Qatar'),
 (SELECT team_id FROM Teams WHERE team_name = 'Ecuador'),
 0, 2,
 (SELECT stadium_id FROM Stadiums WHERE stadium_name = 'Al Bayt Stadium'),
 67372,
 (SELECT referee_id FROM Referees WHERE referee_name = 'Daniele Orsato')
),
('2022-11-21', 'Group B',
 (SELECT team_id FROM Teams WHERE team_name = 'England'),
 (SELECT team_id FROM Teams WHERE team_name = 'Iran'),
 6, 2,
 (SELECT stadium_id FROM Stadiums WHERE stadium_name = 'Khalifa International Stadium'),
 45334,
 (SELECT referee_id FROM Referees WHERE referee_name = 'Raphael Claus')
),
('2022-11-21', 'Group A',
 (SELECT team_id FROM Teams WHERE team_name = 'Senegal'),
 (SELECT team_id FROM Teams WHERE team_name = 'Netherlands'),
 0, 2,
 (SELECT stadium_id FROM Stadiums WHERE stadium_name = 'Al Thumama Stadium'),
 41721,
 (SELECT referee_id FROM Referees WHERE referee_name = 'Wilton Sampaio')
),
('2022-11-21', 'Group B',
 (SELECT team_id FROM Teams WHERE team_name = 'USA'),
 (SELECT team_id FROM Teams WHERE team_name = 'Wales'),
 1, 1,
 (SELECT stadium_id FROM Stadiums WHERE stadium_name = 'Ahmad bin Ali Stadium'),
 43418,
 (SELECT referee_id FROM Referees WHERE referee_name = 'Abdulrahman Al-Jassim')
),
('2022-11-22', 'Group C',
 (SELECT team_id FROM Teams WHERE team_name = 'Argentina'),
 (SELECT team_id FROM Teams WHERE team_name = 'Saudi Arabia'),
 1, 2,
 (SELECT stadium_id FROM Stadiums WHERE stadium_name = 'Lusail Iconic Stadium'),
 88012,
 (SELECT referee_id FROM Referees WHERE referee_name = 'Slavko Vinčić')
),
('2022-11-22', 'Group D',
 (SELECT team_id FROM Teams WHERE team_name = 'Denmark'),
 (SELECT team_id FROM Teams WHERE team_name = 'Tunisia'),
 0, 0,
 (SELECT stadium_id FROM Stadiums WHERE stadium_name = 'Education City Stadium'),
 42925,
 (SELECT referee_id FROM Referees WHERE referee_name = 'César Ramos')
),
('2022-11-22', 'Group C',
 (SELECT team_id FROM Teams WHERE team_name = 'Mexico'),
 (SELECT team_id FROM Teams WHERE team_name = 'Poland'),
 0, 0,
 (SELECT stadium_id FROM Stadiums WHERE stadium_name = 'Stadium 974'),
 39369,
 (SELECT referee_id FROM Referees WHERE referee_name = 'Chris Beath')
),
('2022-11-22', 'Group D',
 (SELECT team_id FROM Teams WHERE team_name = 'France'),
 (SELECT team_id FROM Teams WHERE team_name = 'Australia'),
 4, 1,
 (SELECT stadium_id FROM Stadiums WHERE stadium_name = 'Al Janoub Stadium'),
 40875,
 (SELECT referee_id FROM Referees WHERE referee_name = 'Victor Gomes')
);

-- Insert Goals data
INSERT INTO Goals (match_id, player_id, team_id, minute_scored)
VALUES 
((SELECT match_id FROM Matches WHERE match_date = '2022-11-20' AND team1_id = (SELECT team_id FROM Teams WHERE team_name = 'Qatar')),
 (SELECT player_id FROM Players WHERE player_name = 'Enner Valencia'),
 (SELECT team_id FROM Teams WHERE team_name = 'Ecuador'),
 16),
((SELECT match_id FROM Matches WHERE match_date = '2022-11-20' AND team1_id = (SELECT team_id FROM Teams WHERE team_name = 'Qatar')),
 (SELECT player_id FROM Players WHERE player_name = 'Enner Valencia'),
 (SELECT team_id FROM Teams WHERE team_name = 'Ecuador'),
 31),
((SELECT match_id FROM Matches WHERE match_date = '2022-11-21' AND team1_id = (SELECT team_id FROM Teams WHERE team_name = 'England')),
 (SELECT player_id FROM Players WHERE player_name = 'Bukayo Saka'),
 (SELECT team_id FROM Teams WHERE team_name = 'England'),
 43),
((SELECT match_id FROM Matches WHERE match_date = '2022-11-21' AND team1_id = (SELECT team_id FROM Teams WHERE team_name = 'England')),
 (SELECT player_id FROM Players WHERE player_name = 'Bukayo Saka'),
 (SELECT team_id FROM Teams WHERE team_name = 'England'),
 62),
((SELECT match_id FROM Matches WHERE match_date = '2022-11-21' AND team1_id = (SELECT team_id FROM Teams WHERE team_name = 'England')),
 (SELECT player_id FROM Players WHERE player_name = 'Marcus Rashford'),
 (SELECT team_id FROM Teams WHERE team_name = 'England'),
 71); 